version: '3.8'

services:
  app:
    build: .
    ports:
      - "50051:50051"
    environment:
      - USER_UID=1001  # Set your desired UID
      - USER_NAME=myappuser  # Set your desired username
      - ENV_FILE_CONTENT=DB_CONFIG={"type":"postgres","host":"localhost","user":"postgres", "password":"P@ssw0rd","database":"testd"}
    # Alternative: Mount .env file from host
    # volumes:
    #   - ./.env:/app/.env:ro
